### ISSUE TITLE
Couldn't execute the function successfully

### ISSUE THREAD

**Issue by viggy28** [mukilan88/dictionary#2]
C02YG0S3JGH8:dictionary viggy28$ python main.py
Enter word: abandoned
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    word = input("Enter word: ")
  File "<string>", line 1, in <module>
NameError: name 'abandoned' is not defined
C02YG0S3JGH8:dictionary viggy28$ less data.json
C02YG0S3JGH8:dictionary viggy28$ python main.py
Enter word: contaminated
Traceback (most recent call last):
  File "main.py", line 36, in <module>
    word = input("Enter word: ")
  File "<string>", line 1, in <module>
NameError: name 'contaminated' is not defined

**Comment by mukilan88** [comment]
I think you have add the json file
